name: trackify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  pedometer: ^4.0.1
  permission_handler: ^11.0.0
  provider: ^6.1.1
  
  percent_indicator: ^4.2.2
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  flutter_speed_dial: ^7.0.0
  vibration: ^3.1.3
  url_launcher: ^6.1.12
  image_picker: ^1.0.4
  package_info_plus: ^5.0.1
  health: ^9.0.0
  logger: ^2.0.2
 
dependency_overrides:
  health:
    path: local_plugins/health
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/JockeyOne-Regular.ttf

  fonts:
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/JockeyOne-Regular.ttf

